spring.application.name=ruiji
spring.datasource.url=jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=8215541
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis-Plus ??
mybatis-plus.mapper-locations=classpath:mapper/*.xml  # Mapper XML ????????? XML?
mybatis-plus.type-aliases-package=com.yourpackage.entity  # ????????????
mybatis-plus.global-config.db-config.id-type=ASSIGN_ID
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl  


# ????????MP ???
mybatis-plus.global-config.db-config.logic-delete-field=deleted  # ????????? deleted?0/1 ????/???
